spring.application.name=courseapp
spring.data.mongodb.uri=mongodb+srv://skillshare:courseapp@cluster0.llf5a.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.connection-per-host=50
spring.data.mongodb.min-connections-per-host=10